language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: rX2tSspNxNFVFLTTezO47ljrUVwPlV6JdMkEBVm9DkM7kg2ziF3YXVcT2L6uPk84/mTHGhgSiWgj9oV6yqUHP1xhl/nG5OFfhdrXVQHsEZKXyaqxWFVb7kYiiuEBCdbOankJRCUVKy/iFK3Z6c1Og7kI9ICFUS2SXzxro7QcF9TO0fjDtXECQiCLR9ghtbwblZd92LCTcooUwoQaaczUEOQzhRKFbP+3yRLK9F81XZhOXNcsulj8TyAJKp6JCSUVUpfCAfPejfnHPKAZ56oyF1HrM+qEMzgiyOLQi/zpvoDobG7BqGy5eKkDwrBVBmVCBH9LvNUL3EaaAYIIwpSvEobYL6uuXkfSr5hk/YvrPa8o8S6XeCxTCN21v4mLupcmaN/oR9V2OCQemsPmSk3kyM0EJuY9B7oveNmZUXvbYrk+2ozJHyAf7d4sTMdvrjO+IEEGrP5dlRm5asCQeAyz4kAz8sDLpxsbPiyJvveStAeyuYiORnXQVXEm7wBdSHfLFS9RKqEmmwZCki7/nl0y6wTMcUqoXAGCyDIjjcJ9JpOlGzfVNUCNbKWZ9VRnXVP4V8UN9TwT0R0UUnLFJDZKl42NECANeaLCXgEKUgD/0ZgH2S0V1yu85PwzwCij0kF432+4MBcWmG+ax9lSJMmj2wpifqO7rgBOX4gwzgbWg1E=
  app: protected-earth-78962
  on:
    repo: Richardek/node-shopping-list-integration-tests
