language: node_js
node_js: node
deploy: shielded-caverns-36633
  provider: heroku
  api_key:
    secure: MzL0AYkeG5T2Jl7eGWZ12p1neEvPATG+8yDEi8biwRN9cmnrFM1v8UW+cCIXleZo6DlEilcZxuKtpJQPffa98MexN2E94FsXmJk3d4IPD/aUChVts5B6pnPb86aNfefzI9CfHAygBVFeCsbgm79P6/Srz22ygvyURKxDUMiC+dc1jtINLlW/QCSIwz4IWDzjIzOMeTpc8yOG8Uh/xB5UKKcdLgWn97xtbABIr87AvwX878ChiSGS9KfsxZpOUKERclj3gUWNomM5eUp5woKXx8q14eujQgI4foFmeTW5BdSdKHwR/hxerr+hhLpWDQEFJ4gNP7E9DvsPSpgu3ZntLmEOp/Y/RAD7ptA80Ti7MllOWfoKMyC6bbjl8Nk0ImIvNLppNwVaJhvaC1a/AXYvrhnMNkPvOlFzb7XOnbbY5Wue+n97mcSNj1D7xnSAYbyRfao3yCrYJHyz2PIUL7m3Lq3ovFTSx8d6kU4jeS1ok8lb4r20XO2ipk2HLhNJQzndmTi2TqvAy7PreuYzhvljhC8Zq6XrNhRZTdMVH0sydFnv4g0oVO8gsI1IXysBhgjRprNLa/W67UlqEdl70Cinm2g708Vtzb6DkY4CM/UE5cKQ2Zbh+cf3uu+bmTM2IA+Bgmg1ToHzm4rb164mZtepo5ObJvIsa35TU4jaSQPjUtU=
  app: node-shopping-list-integration-tests
  on:
    repo: Richardek/node-shopping-list-integration-tests
